### PR TITLE
Improvements to coin selection

### PR DESCRIPTION
**Pull request by alecalve**
- Try to create change outputs worth at least 0.01 BTC
- Try to find a single coin that'll pay for the transaction without resulting in a change output to lower fees (unlikely, but cheap to compute)
- Added an optional privacy filter (toggled by `filterAddresses`) that minimizes the number of unique input addresses used at the expense of a potentially higher fee.

### CODE REVIEW

**Comment by Sjors** [comment]
Lets wait until at least next week for this.

**Comment by pernas** [comment]
@sjors what we should do with this one?

**Comment by Sjors** [comment]
Indeed, what should we do?

**Comment by BangLy** [comment]
Where is the link can find the private keys..can selet all the keys for easy confrimation

**Comment by Sjors** [comment]
Closing PR, pending a broader refactor that decouples coin selection.

**Pull request closed without merging**
