### PR TITLE
Upgrade ws to v1.1.0

### PR DESCRIPTION
**Pull request by jtormey**
Includes
* Patch for Buffer memory allocation vulnerability cc @kristovatlas, https://github.com/websockets/ws/commit/29293ed11b679e0366fa0f6bb9310b330dafd795
* Fix for zlib related crash in node, https://github.com/websockets/ws/commit/4bf5fb8233ac4aacc358639f53644ed26cc8c320, https://github.com/websockets/ws/issues/628

### CODE REVIEW

**Comment by kristovatlas** [comment]
Huzzah!

**Comment by kristovatlas** [comment]
Looks like @jtormey's patch for using ws with browserify is based on this deletion in ws: https://github.com/websockets/ws/commit/e54d45fbab3b19c2940e9057ce1e7b8f105873e0

**Comment by kristovatlas** [comment]
utACK

**Comment by Sjors** [comment]
Did you test this in at least IE 11, Chrome, Safari and Firefox?

**Comment by jtormey** [comment]
Tested on all of those + Edge

**Pull request merged**
