### PR TITLE
Removed dead code

### PR DESCRIPTION
**Pull request by alecalve**

### CODE REVIEW

**Comment by pernas** [comment]
There are several things here:

1) API class should implement a timeout. We should investigate the way how to do that using fetch.
2) Are you sure walletstore countries and languages thing is dead code. This is not definitely the place for that but i think somebody maybe ios or webwallet is using it (or it was) Did you check if it is used there?

**Comment by alecalve** [comment]
I checked for usage in the other repos before removing any code.

**Comment by pernas** [comment]
nice

**Comment by Sjors** [comment]
There might be some overlap with #54 but that's fine. 

I'll double check this for web. 

@woudini can you ACK this for iOs?

**Comment by pernas** [comment]
ack.

AJAX_TIMEOUT must be back. iOS is setting it and we will implement it.

**Comment by Sjors** [comment]
Retro ACK :-)

**Comment by woudini** [comment]
Sorry @Sjors , super retro ACK and thanks @pernas

**Pull request merged**
