### PR TITLE
Save metadata hdnode on metadata service (for second password)

### PR DESCRIPTION
**Pull request by pernas**

### CODE REVIEW

**Comment by Sjors** [comment]
I don't like making the login functionality more complex that it already is. I also don't think it's a good user experience to ask for the second password during login.

How about this approach:

Upon login:
* if `wallet. _metadataHDNode` is present, use it
* if `wallet. _metadataHDNode` is absent and not 2nd password is set, generate it, use it and save the wallet
  * this will cause a lot wallet saves to happen after we deploy this
*  if `wallet. _metadataHDNode` is absent and 2nd password is set, don't external (current behavior)

Add a function `wallet.setMetadataHDNode(secondPassword)`, which derives and saves `wallet. _metadataHDNode`. This can be called by the frontend at any time. For instance, if the user wants to visit the buy tab for the first time, we ask them to enter their second password, and then call this method. We then ask the user to login again.

cc @jtormey, @larskrueger

**Comment by pernas** [comment]
Well, the think is that everytime we have more and more things depending on metadata. We are introducing the contacts lists and payment requests. Matt is thinking in another feature for watch only wallets that it is going to use metadata to store partial transactions and I am sure many other cases will come. So being sure that metadatahdnode is loaded after login will make all this things easier. 

Not to say, that the friction for this is really low. A really low percentage of users has second password and this second password ask it is only going to happen only once in the wallet lifetime.

**Comment by Sjors** [comment]
All these features need to do is check some flag like `wallet.metadataReady`, and if false, ask for the 2nd password. That can happen immediately after login, just like how we handle the v2 -> v3 upgrade.

**Comment by pernas** [comment]
Yes, you can do that, but I think it is a mess. In general, not knowing if you data is there and constantly checking for its existence it is kind of painful. But with metadata it is not only that. Know we are talking about not even knowing if you can load it.

**Comment by Tintress15** [comment]
Try here

**Comment by Sjors** [comment]
This has been merged manually.

**Pull request closed without merging**
