### PR TITLE
v3.42 release

### PR DESCRIPTION
**Pull request by plondon**

### CODE REVIEW

**Comment by SonHoangHa770** [comment]
Ban gui cho toi vi dien tu cua ban cho toi nhe

**Comment by SonHoangHa770** [comment]
Banco tien gui cho toi xin 200 usd vao tai khoan de dung tieu tet am lich viet nam , tai khoan la :Doan van son :102000784668..manghan hang.ICBVVNVX162 .Thanks you

**Comment by 3230zahar** [comment]
[496.patch.txt](https://github.com/blockchain/My-Wallet-V3/files/1691990/496.patch.txt)

**Comment by leonwaljer** [comment]
Ok this is going. To be find and their may need to be an extended time
frame as braintree/PayPal don't process. Over the week end but the 10
bit/cypo that you. Are send to me is going to make so many important people
here very happy thank you so much

**Comment by leonwaljer** [comment]
One real comment is one of your asdoiates ding on from Vietnam donvanson 102000748668 1CBVVNX162 a lot if fancy writing but I gave say obevcoin show up yet

**Comment by SonHoangHa770** [comment]
Mua ban bitcoin o trong github duoc khong ,
Vào 14-02-2018 20:57, "kingofbabes" <notifications@github.com> đã viết:

**Pull request merged**
