### PR TITLE
Update whitelist: create-hmac, create-hash, sha.js, added cipher-base 

### PR DESCRIPTION
**Pull request by Sjors**
https://github.com/crypto-browserify/createHmac/compare/v1.1.3...v1.1.4
https://github.com/crypto-browserify/createHash/compare/1.1.1...v1.1.2
https://github.com/crypto-browserify/cipher-base/blob/master/index.js
https://github.com/crypto-browserify/sha.js/compare/v2.4.2...v2.4.4

### CODE REVIEW

**Comment by Sjors** [comment]
Partial overlap with @pernas commit: https://github.com/blockchain/My-Wallet-V3/commit/9823a65d6d493f384ff713c7cb2249c79d8e2dd1

**Comment by kristovatlas** [comment]
ACK https://github.com/crypto-browserify/createHmac/compare/v1.1.3...v1.1.4

**Comment by kristovatlas** [comment]
The change over to the new CipherBase class from nodejs's built in class used in the previous version is quite difficult to audit. AFAICT the nodejs class is actually a C++ library, so it's not like you can do an easy side-by-side comparison. :-/

**Comment by kristovatlas** [comment]
The change in https://github.com/crypto-browserify/sha.js/compare/v2.4.2...v2.4.4 is mostly arithmetic changes that are cumbersome to review, but as long as the class is spitting out the right hashes it should be fine. I would like to see a quick comparison written for this comparing the outputs of the old and new version for some random inputs.

**Comment by Sjors** [comment]
sha.js comes with its own tests and vectors: https://github.com/crypto-browserify/sha.js/tree/master/test

You could modify one of the test vectors and re-run the test suite.

**Comment by kristovatlas** [comment]
I won't have a chance to do that soon, so merging for now.

**Pull request merged**
