### PR TITLE
Refactor import export

### PR DESCRIPTION
**Pull request by alecalve**
* Moved scrypt crypto function to wallet-crypto
* Removed callbacks from parseBIP38toECKey and made it into a promise
* Implemented tighter checks on scrypt parameters

parseBIP38toECKey is now the only function remaining in import-export. I didn't kill the file completely this time as moving the function to wallet-crypto would require BIP-38 tests to be modified.

Tested it using the frontend and a paperwallet from bitaddress.

### CODE REVIEW

**Comment by jtormey** [comment]
In iOS, the scrypt function is [overwritten here](https://github.com/blockchain/My-Wallet-V3-iOS/blob/master/Blockchain/js/wallet-ios.js#L1011-L1027) with native code, so that it doesn't run slowly on mobile. @woudini will need to override scrypt in WalletCrypto rather than in ImportExport after this is merged.

**Comment by alecalve** [comment]
Oh thanks for noticing that!

**Comment by Sjors** [comment]
I did a rebase on master and then tried to import this test vector:
6PRW9MLy8xUZainNKPjQSaW1yWZQsokaFGMj7g2ZyvdD8xBU88Jnhbu4WU
Password: 1234

"Nothing happens"

See also the official test vectors.

Can you check what's going on and also rebase the branch?

**Comment by Sjors** [comment]
Not strictly necessary, but I'm going to wait for and rebase this on #174.

**Comment by Sjors** [comment]
@alecalve can you rebase this?

**Comment by alecalve** [comment]
I tried to rebase it but cannot get the tests to pass. It's been too long since I touched this code. I'll close this PR and redo this refactor later.

**Pull request closed without merging**
