### PR TITLE
refactor(ImportExport): remove ImportExport module

### PR DESCRIPTION
**Pull request by jtormey**

### CODE REVIEW

**Comment by Sjors** [comment]
What are you trying to achieve and how can I help?

**Comment by jtormey** [comment]
The idea was to remove ImportExport and replace it with the [bip38](https://github.com/bitcoinjs/bip38) library. The issue is that the Crypto_scrypt function in ImportExport is overwritten in iOS with native code for performance. So, I don't know how possible it is to achieve this.

**Comment by Sjors** [comment]
Can you rebase this on top of #54?

**Comment by jtormey** [comment]
Closing because this requires a time investment that does not make sense at the moment.

**Pull request closed without merging**
