### PR TITLE
refactor(NPM): test with node v5.8 (npm v3.8.0)

### PR DESCRIPTION
**Pull request by Sjors**
Reopening from #171 

`npm shrinkwrap` suddenly includes dev dependencies, which breaks my dependency script.

- [x] Depends on #175

### CODE REVIEW

**Comment by pernas** [comment]
(bytelength vs length)

I have been reading about it and both seems to be properties of ArrayBuffer.prototype.  Bytelength is number of bytes and length is the number of elements of the array. I think for our case coincide since we are creating arrays of bytes (we are not manipulating strings). The weird stuff is that Buffer is not ArrayBuffer. Maybe for the browserified version it is but not in phantom js and this would explain the missing property there?

@jtormey any thoughts?

**Comment by jtormey** [comment]
In the Node docs, [Buffer](https://nodejs.org/api/buffer.html#buffer_buf_length) only has a `length` property. Since browserify tries to mirror Node exactly, I think it's better to use length rather than byteLength.

**Comment by pernas** [comment]
@sjors after Justin investigation and talk we think that the way to go is using .length everywhere. If you want to fix it.

**Comment by Sjors** [comment]
Done.

**Comment by pernas** [comment]
ack

**Pull request merged**
