### PR TITLE
feat(pass hint): main pass and sec pass not allowed as hint

### PR DESCRIPTION
**Pull request by pernas**
the frontend should handle the new errors to show notifications

### CODE REVIEW

**Comment by kristovatlas** [comment]
what's with the magic error numbers: 101, 102, 103?

**Comment by pernas** [comment]
it is to avoid writing the error message here so the frontend can localize it. But we should have a better error system...

**Comment by kristovatlas** [comment]
For the sake of people reading who didn't write the code, might I suggest at least an enum that defines the various errors as human-readable constants?

**Comment by Sjors** [comment]
I like Kristov's suggestion about enums, how well do those work in Javascript?

**Comment by jtormey** [comment]
Enums don't really exist in JavaScript. The best we can do is to define an object in a module that maps error constants to their respective codes:

```js
module.exports = {
    ERR_PASS : 100,
    ERR_DECRYPT : 200
};
```

And then use like this:

```js
var wallet = require('./blockchain-wallet');
var ecodes = require('./error-codes');

wallet.decryptWallet().catch(function (err) {
    console.log(err);
    throw ecodes.ERR_DECRYPT;
});
```

**Comment by jtormey** [comment]
Or, have it map error constants to description strings:

```js
module.exports = {
    ERR_PASS : 'Wrong password was entered',
    ERR_DECRYPT : 'Something went failed during decryption'
};
````

**Comment by Sjors** [comment]
That's already a lot more readable. We don't need the human readable strings, as the frontend and iOs app should care of that.

**Comment by kristovatlas** [comment]
Justin, that first example is just what I was thinking. Thanks!

**Pull request merged**
