### PR TITLE
Expose functions to iOS for use with JavaScriptCore

### PR DESCRIPTION
**Pull request by woudini**
- Exposed `stretchPassword()` to be overridden by iOS.
- Exposed `randomBytes()` to be overridden by iOS.
- Exposed websocket functions to be overridden by iOS.
- Moved `decryptSuccess()` to be called after initialization of wallet object.
- Added `&& message.data` here to prevent an error `SyntaxError: JSON Parse error: Unexpected identifier "undefined"` https://github.com/blockchain/My-Wallet-V3/compare/javaScriptCore?expand=1#diff-7d6391c0ab1c356fc9d1e26ef9c4fc67R58
- Deleting this line was the only way I could get this test to pass. Not sure if there is a better way to expose `stretchPassword()`. https://github.com/blockchain/My-Wallet-V3/compare/javaScriptCore?expand=1#diff-1d1d10df861e697cf933c59b203329c1L119

### CODE REVIEW

**Comment by Sjors** [comment]
utACK

**Comment by Sjors** [comment]
@jtormey @pernas if there are no issues, I suggest merging this before the pre-release tomorrow.

**Comment by Sjors** [comment]
Make sure to use the "squash commit" option when merging this.

**Comment by pernas** [comment]
ack

**Pull request merged**
