### PR TITLE
v3.41-release

### PR DESCRIPTION
**Pull request by plondon**
Requires https://github.com/blockchain/service-explorer/pull/275

### CODE REVIEW

**Comment by leonwaljer** [comment]
Looking to transfur any funds aviabke to pay for serguru for my wife

**Comment by leonwaljer** [comment]
Need help receivingvone bit coin transfurbto PayPal/me/45 walkerleon865@Gmail.com. Merchant accountnoVr2ELX3LHFT3C

**Comment by leonwaljer** [comment]
Need help receivingvone bit coin transfurbto PayPal/me/45 walkerleon865@Gmail.com. Merchant accountnoVr2ELX3LHFT3C

**Comment by leonwaljer** [comment]
Have these funds already. Went to paypal

**Comment by leonwaljer** [comment]
This is Mr Walker Retired Military Non Commission. Officer that you for.
Your reponce in all reality. The fact on the matter. Is I have been
involved what bitcoin since 2013 and have yet to spend one red cent if
those. Funds I hoping all that's about tkt change. My business Ricks.
Rolling. Auto is a service. Fir the public fir those. Who cent afford to
take their car to the shoal or have it towed with thus new lightyku just
shine Im hoping. To get funded with at lease. One bit coin. Into my
PayPal.business account by close. Of business. To day

**Comment by yerarse** [comment]
lve never used paypal with bitcoin
    On Tuesday, 30 January 2018, 21:37:09 GMT, Leon <notifications@github.com> wrote:  
 
 
Have these funds already. Went to paypal

**Comment by leonwaljer** [comment]
Did you send coins to PayPal already if you didvthatvwiukd be great

**Comment by leonwaljer** [comment]
Ok Gentlemen lets sit back and take a braver Im really excited about enter acting. With such heads of the table respely. Your leaving.  Of the field puts me in good field position. I can sure you that your. Accounts. Are well and secured Im an honorable gentleman youvwill be fine you have my word on that. Now may AI have your word sir and i assume you. Speak for your colies. That my electronic/bitcoins with be sent to me with god speed You mention that you don't deal with PayPal so heres my routing number and account. Number could you kindly. Send me a bank transfer their

**Comment by leonwaljer** [comment]
R0:031101169 and account number :156104658166 OR BETTER THAT THAT SO I KNOW THAT WE ARE DRIVING THE. SAME CAR YOU SEND ME A CASHIER. CHECK BY FEDEX EXPRESS. ALONG WITH. DOCUMENTATION AND I WILL SIGN ANY NECESSARY. DOCUMENTS YOU WANT ME TO ENTERTAIN. OR YOU CAN SEND THEM TO ME CONSENT SIGN MY MAILING ADRRESSVIS 800 COLD CREEK DRIVE. ARLINGTON TX 76002 PHONE NUMBER 817-443-4842 your response. Is reqyested

**Comment by charlesrutabanzibwa** [comment]
I'm much grateful for hard work you have undergone in tackling the
underlying issue.Too much congratulations!I was totally upset
psychologically and attended clinical checkup for six hours.May I call
you a blessed man.Let you be the saved along God's blessings. We
Tanzanians do not employ Paypals nor BitCards as you do in
America.Bank transfer is accepted only account need for you to
transfer funds to my account by TT(telegraphic transfer).herewith find
my Bank account detailsBANK NAME:-NMB,    ACCOUNT NAME:-CHARLES PAUL
RUTABANZIBWA, ACCOUNT NUMBER:-31808000140                   Using Bank
Transfer in America Banks will credit my account with the funds
remitted by Blockchain to my account stated above:Please do the same
and let me know by mailing me. Much regards.Charles Rutabanzibwa.

**Comment by leonwaljer** [comment]
Ok I will work with you because you are making the right moves now let me
get this. Train out if natural and get it into gear

**Pull request merged**
